function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed");el.html("<span class=\"t142__text\">"+btntext+"</span>")}}}
function t270_scroll(hash,offset){var $root=$('html, body');var target="";try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length==0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length==0){return!0}}
$root.animate({scrollTop:target.offset().top-offset},500,function(){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}});return!0}
function t446_setLogoPadding(recid){if($(window).width()>980){var t446__menu=$('#rec'+recid+' .t446');var t446__logo=t446__menu.find('.t446__logowrapper');var t446__leftpart=t446__menu.find('.t446__leftwrapper');var t446__rightpart=t446__menu.find('.t446__rightwrapper');t446__leftpart.css("padding-right",t446__logo.width()/2+50);t446__rightpart.css("padding-left",t446__logo.width()/2+50)}}
function t446_checkOverflow(recid,menuheight){var t446__menu=$('#rec'+recid+' .t446');var t446__rightwr=t446__menu.find('.t446__rightwrapper');var t446__rightmenuwr=t446__rightwr.find('.t446__rightmenuwrapper');var t446__rightadditionalwr=t446__rightwr.find('.t446__additionalwrapper');var t446__burgeroverflow=t446__rightwr.find('.t446__burgerwrapper_overflow');var t446__burgerwithoutoverflow=t446__rightwr.find('.t446__burgerwrapper_withoutoverflow');if(menuheight>0){var t446__height=menuheight}else{var t446__height=80}
if($(window).width()>980&&(t446__rightmenuwr.width()+t446__rightadditionalwr.width())>t446__rightwr.width()){t446__menu.css("height",t446__height*2);t446__rightadditionalwr.css("float","right");t446__burgeroverflow.css("display","table-cell");t446__burgerwithoutoverflow.css("display","none")}else{if(t446__menu.height()>t446__height){t446__menu.css("height",t446__height)}
if(t446__rightadditionalwr.css("float")=="right"){t446__rightadditionalwr.css("float","none")}
t446__burgeroverflow.css("display","none");t446__burgerwithoutoverflow.css("display","table-cell")}}
function t446_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="index.html"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="index.html"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="index.html"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t446__list_item a[href='"+url+"']").addClass("t-active");$(".t446__list_item a[href='"+url+"/']").addClass("t-active");$(".t446__list_item a[href='"+pathname+"']").addClass("t-active");$(".t446__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t446__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t446__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t446_checkAnchorLinks(recid){if($(window).width()>=960){var t446_navLinks=$("#rec"+recid+" .t446__list_item a:not(.tooltipstered)[href*='#']");if(t446_navLinks.length>0){t446_catchScroll(t446_navLinks)}}}
function t446_catchScroll(t446_navLinks){var t446_clickedSectionId=null,t446_sections=new Array(),t446_sectionIdTonavigationLink=[],t446_interval=100,t446_lastCall,t446_timeoutId;t446_navLinks=$(t446_navLinks.get().reverse());t446_navLinks.each(function(){var t446_cursection=t446_getSectionByHref($(this));if(typeof t446_cursection.attr("id")!="undefined"){t446_sections.push(t446_cursection)}
t446_sectionIdTonavigationLink[t446_cursection.attr("id")]=$(this)});t446_updateSectionsOffsets(t446_sections);t446_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t446_updateSectionsOffsets(t446_sections)},200));$('.t446').bind('displayChanged',function(){t446_updateSectionsOffsets(t446_sections)});setInterval(function(){t446_updateSectionsOffsets(t446_sections)},5000);t446_highlightNavLinks(t446_navLinks,t446_sections,t446_sectionIdTonavigationLink,t446_clickedSectionId);t446_navLinks.click(function(){var t446_clickedSection=t446_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t446_clickedSection.attr("id")!="undefined"){t446_navLinks.removeClass('t-active');$(this).addClass('t-active');t446_clickedSectionId=t446_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t446_now=new Date().getTime();if(t446_lastCall&&t446_now<(t446_lastCall+t446_interval)){clearTimeout(t446_timeoutId);t446_timeoutId=setTimeout(function(){t446_lastCall=t446_now;t446_clickedSectionId=t446_highlightNavLinks(t446_navLinks,t446_sections,t446_sectionIdTonavigationLink,t446_clickedSectionId)},t446_interval-(t446_now-t446_lastCall))}else{t446_lastCall=t446_now;t446_clickedSectionId=t446_highlightNavLinks(t446_navLinks,t446_sections,t446_sectionIdTonavigationLink,t446_clickedSectionId)}})}
function t446_updateSectionsOffsets(sections){$(sections).each(function(){var t446_curSection=$(this);t446_curSection.attr("data-offset-top",t446_curSection.offset().top)})}
function t446_getSectionByHref(curlink){var t446_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t446_curLinkValue[0]=='index.html'){t446_curLinkValue=t446_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t446_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t446_curLinkValue.substring(1)+"']")}}
function t446_highlightNavLinks(t446_navLinks,t446_sections,t446_sectionIdTonavigationLink,t446_clickedSectionId){var t446_scrollPosition=$(window).scrollTop(),t446_valueToReturn=t446_clickedSectionId;if(t446_sections.length!=0&&t446_clickedSectionId==null&&t446_sections[t446_sections.length-1].attr("data-offset-top")>(t446_scrollPosition+300)){t446_navLinks.removeClass('t-active');return null}
$(t446_sections).each(function(e){var t446_curSection=$(this),t446_sectionTop=t446_curSection.attr("data-offset-top"),t446_id=t446_curSection.attr('id'),t446_navLink=t446_sectionIdTonavigationLink[t446_id];if(((t446_scrollPosition+300)>=t446_sectionTop)||(t446_sections[0].attr("id")==t446_id&&t446_scrollPosition>=$(document).height()-$(window).height())){if(t446_clickedSectionId==null&&!t446_navLink.hasClass('t-active')){t446_navLinks.removeClass('t-active');t446_navLink.addClass('t-active');t446_valueToReturn=null}else{if(t446_clickedSectionId!=null&&t446_id==t446_clickedSectionId){t446_valueToReturn=null}}
return!1}});return t446_valueToReturn}
function t446_setPath(){}
function t446_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t446").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t446").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t446_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t446").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t446_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t446").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t446_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t446"),burger=el.find(".t446__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t446_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t635_init(recid){t635_startType(recid)}
function t635_startType(recid){var t635_el=$('#rec'+recid),t635_data=t635_el.find(".t635__textholder"),t635_animRecId=t635_data.attr("data-recid"),t635_animText=t635_findAnimElem(t635_animRecId),t635_phrasesList=[],t635_phrase1=t635_data.attr("data-text1"),t635_phrase2=t635_data.attr("data-text2"),t635_phrase3=t635_data.attr("data-text3"),t635_phrase4=t635_data.attr("data-text4"),t635_phrase5=t635_data.attr("data-text5"),t635_speed=t635_data.attr("data-speed"),t635_loop=t635_data.attr("data-loop"),t635_backspaceDelay=t635_data.attr("data-backspacing-delay");if(typeof t635_animText=="undefined"){return}
if(typeof t635_phrase1!="undefined"){t635_phrasesList.push(t635_phrase1.slice(0,80))}
if(typeof t635_phrase2!="undefined"){t635_phrasesList.push(t635_phrase2.slice(0,80))}
if(typeof t635_phrase3!="undefined"){t635_phrasesList.push(t635_phrase3.slice(0,80))}
if(typeof t635_phrase4!="undefined"){t635_phrasesList.push(t635_phrase4.slice(0,80))}
if(typeof t635_phrase5!="undefined"){t635_phrasesList.push(t635_phrase5.slice(0,80))}
if(t635_animText.length!=0&&t635_phrasesList.length!=0){var t635_animTextHtml=t635_animText.html(),t635_animTextSplitted=t635_animTextHtml.split("|"),t635_curWin=$(window);t635_animText.html(t635_animTextSplitted[0]+"<span class=\"t635__typing-text\"></span>"+t635_animTextSplitted[1]);t635_updateAnimTextLimits(t635_animRecId);t635_curWin.bind('resize',t_throttle(function(){t635_updateAnimTextLimits(t635_animRecId)},200));setInterval(function(){t635_updateAnimTextLimits(t635_animRecId)},5000);var t635_animatedText=$("#rec"+t635_animRecId+" .t635__typing-text"),t635_animTextTop=t635_animatedText.attr("data-top-limit"),t635_animTextBottom=t635_animatedText.attr("data-bottom-limit"),t635_winTop=t635_curWin.scrollTop(),t635_winBottom=t635_winTop+t635_curWin.height();t635_animateText(t635_animRecId,t635_phrasesList,t635_speed,t635_loop,t635_backspaceDelay);if(t635_animTextBottom<t635_winTop||t635_animTextTop>t635_winBottom){$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').pauseTyping();$("#rec"+t635_animRecId+" .t635__typing-text").html("")}
t635_curWin.bind('scroll',t_throttle(function(){t635_animTextTop=t635_animatedText.attr("data-top-limit");t635_animTextBottom=t635_animatedText.attr("data-bottom-limit");t635_winTop=t635_curWin.scrollTop();t635_winBottom=t635_winTop+t635_curWin.height();if(t635_animTextBottom<t635_winTop||t635_animTextTop>t635_winBottom){$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').pauseTyping();$("#rec"+t635_animRecId+" .t635__typing-text").html("")}else{$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').continueTyping()}},200))}}
function t635_findAnimElem(animRecId){var animRec=$("#rec"+animRecId);var animH1=animRec.find("h1:contains(\'|\')").last();var animH2=animRec.find("h2:contains(\'|\')").last();var animH3=animRec.find("h3:contains(\'|\')").last();var animDiv=animRec.find("div:contains(\'|\')").last();if(typeof animH1!="undefined"&&animH1.length>0){return animH1}
if(typeof animH2!="undefined"&&animH2.length>0){return animH2}
if(typeof animH3!="undefined"&&animH3.length>0){return animH3}
if(typeof animDiv!="undefined"&&animDiv.length>0){return animDiv}}
function t635_updateAnimTextLimits(t635_animRecId){var t635_animatedBlock=$("#rec"+t635_animRecId),t635_animatedText=t635_animatedBlock.find(".t635__typing-text");t635_animatedText.attr("data-top-limit",t635_animatedText.offset().top);t635_animatedText.attr("data-bottom-limit",(t635_animatedBlock.offset().top+t635_animatedBlock.height()))}
function t635_animateText(t635_animRecId,t635_phrasesList,t635_speed,t635_loop,t635_backspaceDelay){if(typeof t635_speed=="undefined"){t635_speed=40}
if(typeof t635_backspaceDelay=="undefined"){t635_backspaceDelay=800}
if(typeof t635_loop=="undefined"){t635_loop=!0}else{t635_loop=!1}
$("#rec"+t635_animRecId+" .t635__typing-text").typed({strings:t635_phrasesList,typeSpeed:t635_speed*1,startDelay:600,backSpeed:10,backDelay:t635_backspaceDelay*1,loop:t635_loop,contentType:'text'})}
function t668_init(recid){var el=$('#rec'+recid),toggler=el.find(".t668__header");toggler.click(function(){$(this).toggleClass("t668__opened");$(this).next().slideToggle();if(window.lazy=='y'){t_lazyload_update()}})}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$("#rec"+recid),play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$("#rec"+recid),body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$("#rec"+recid);var image=el.find(".t670__separator");image.each(function(){var width=$(this).attr("data-slider-image-width");var height=$(this).attr("data-slider-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t706_onSuccessCallback(t706_form){$(".t706__cartwin-products").slideUp(10,function(){});$(".t706__cartwin-bottom").slideUp(10,function(){});$(".t706 .t-form__inputsbox").slideUp(700,function(){});try{tcart__unlockScroll()}catch(e){}}
function t776__init(recid){setTimeout(function(){t_prod__init(recid);t776_initPopup(recid);t776__hoverZoom_init(recid);t776__updateLazyLoad(recid);t776__alignButtons_init(recid)},500)}
function t776__alignButtons_init(recid){var rec=$('#rec'+recid);if(rec.find('[data-buttons-v-align]')[0]){try{t776__alignButtons(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t776__alignButtons(recid)},200));$('.t776').bind('displayChanged',function(){t776__alignButtons(recid)});if($isMobile){$(window).on('orientationchange',function(){t776__alignButtons(recid)})}}catch(e){console.log('buttons-v-align error: '+e.message)}}}
function t776__alignButtons(recid){var rec=$('#rec'+recid);var wrappers=rec.find('.t776__textwrapper');var maxHeight=0;var itemsInRow=rec.find('.t-container').attr('data-blocks-per-row')*1;var mobileView=$(window).width()<=480;var tableView=$(window).width()<=960&&$(window).width()>480;var mobileOneRow=$(window).width()<=960&&rec.find('.t776__container_mobile-flex')[0]?true:!1;var mobileTwoItemsInRow=$(window).width()<=480&&rec.find('.t776 .mobile-two-columns')[0]?true:!1;if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var i=1;var wrappersInRow=[];$.each(wrappers,function(key,element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
$.each(wrappersInRow,function(key,wrapper){wrapper.style.height=maxHeight+'px'});if(i===itemsInRow){i=0;maxHeight=0;wrappersInRow=[]}
i++}})}
function t776__hoverZoom_init(recid){if(isMobile){return}
var rec=$('#rec'+recid);try{if(rec.find('[data-hover-zoom]')[0]){if(!jQuery.cachedZoomScript){jQuery.cachedZoomScript=function(url){var options={dataType:'script',cache:!0,url:url};return jQuery.ajax(options)}}
$.cachedZoomScript('../static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js').done(function(script,textStatus){if(textStatus=='success'){setTimeout(function(){t_hoverZoom_init(recid,".t-slds__container")},500)}else{console.log('Upload script error: '+textStatus)}})}}catch(e){console.log('Zoom image init error: '+e.message)}}
function t776__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t776__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){t_lazyload_update()},500))}}
function t776_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').each(function(e){var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');$(".r").find('a[href$="#!/tproduct/'+recid+'-'+lid_prod+'"]').click(function(e){if(rec.find('[data-product-lid='+lid_prod+']').length){rec.find('[data-product-lid='+lid_prod+'] [href^="#prodpopup"]').triggerHandler('click')}})});rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_sldsInit(recid+' #t776__product-'+lid_prod+'')});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();t776_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]');el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23%21/tproduct/index.html')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t776_updateSlider(recid+' #t776__product-'+lid_prod+'');if(window.lazy=='y'){t_lazyload_update()}});if($('#record'+recid).length==0){t776_checkUrl(recid)}
t776_copyTypography(recid)}
function t776_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23%21/tproduct/index.html')}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t776_updateSlider(recid){var el=$('#rec'+recid);t_slds_SliderWidth(recid);var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_slds_UpdateSliderHeight(recid);t_slds_UpdateSliderArrowsHeight(recid)}
function t776_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy=='y'){t_lazyload_update()}},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t776_closePopup()}});el.find('.t-popup__close, .t776__close-text').click(function(e){t776_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t776_closePopup()}})}
function t776_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23%21/tproduct/index.html')}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t776_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t776_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t776__title').attr('style');var descrStyle=rec.find('.t776__descr').attr('style');rec.find('.t-popup .t776__title').attr("style",t776_removeSizeStyles(titleStyle));rec.find('.t-popup .t776__descr, .t-popup .t776__text').attr("style",t776_removeSizeStyles(descrStyle))}
function t796_init(recid){var el=$("#rec"+recid);var shapeEl=el.find(".t796__shape-border");var recs=el.find(".t796").attr("data-shape-rec-ids");if(typeof recs!="undefined"){recs=recs.split(",");recs.forEach(function(rec_id,i,arr){var curRec=$("#rec"+rec_id);var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)})}else{var excludes="[data-record-type='215'],[data-record-type='706'],[data-record-type='651'],[data-record-type='825'],[data-record-type='708']";if(shapeEl.hasClass('t796__shape-border_top')||shapeEl.hasClass('t796__shape-border_top-flip')){var curRec=el.next(".r");if(curRec.is(excludes)){curRec=curRec.next(".r")}}
if(shapeEl.hasClass('t796__shape-border_bottom')||shapeEl.hasClass('t796__shape-border_bottom-flip')){var curRec=el.prev(".r");if(curRec.is(excludes)){curRec=curRec.prev(".r")}}
if(curRec.length!=0){var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)}}}
function t796_addDivider(curRec,curShapeEl){curRec.attr("data-animationappear","off").removeClass('r_hidden');var coverWrapper=curRec.find(".t-cover");var zeroWrapper=curRec.find(".t396");if(coverWrapper.length>0||zeroWrapper.length>0){if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(curShapeEl)}
if(zeroWrapper.length>0){zeroWrapper.after(curShapeEl);curRec.css("position","relative")}
curShapeEl.css("display","block")}else{var wrapper=curRec;var curRecType=curRec.attr("data-record-type");if(wrapper.length==0){return!0}
wrapper.append(curShapeEl);wrapper.css("position","relative");if(curRecType!="554"&&curRecType!="125"){wrapper.children("div").first().css({"position":"relative","z-index":"1"}).addClass("t796_cont-near-shape-divider")}
if(curRecType=="734"||curRecType=="675"||curRecType=="279"||curRecType=="694"||curRecType=="195"){curShapeEl.css("z-index","1")}
curShapeEl.css("display","block")}}
function t796_setColor(el,curShapeEl){if(typeof curShapeEl.attr("data-fill-color")!="undefined"){return}
if(curShapeEl.hasClass("t796__shape-border_bottom")||curShapeEl.hasClass("t796__shape-border_bottom-flip")){var nearestBlock=el.next(".r")}else{var nearestBlock=el.prev(".r")}
if(nearestBlock.length==0){return}
var fillColor=nearestBlock.attr("data-bg-color");if(typeof fillColor=="undefined"){return}
curShapeEl.find(".t796__svg").css("fill",fillColor)}